trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - script: printenv
    displayName:  display env vars

  - script: packer init $(Build.SourcesDirectory)/CHAP08/packer/.pkr.hcl
    displayName:  Packer init

  - script: packer validate $(Build.SourcesDirectory)/CHAP08/packer/.pkr.hcl
    displayName: Packer validate template

  - script: packer build $(Build.SourcesDirectory)/CHAP08/packer/.pkr.hcl
    displayName: Packer build template